### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by ghost** [navdeepsingh/react-quiz-app#1]
How to start the app?

**Comment by navdeepsingh** [comment]
Seems code become obsolete, tried too local to start but many dependencies failures local. Lemme know if you able to start it. Followed these like links https://medium.com/@ahsan.ayaz/beginners-guide-to-webpack-how-to-start-a-basic-application-with-webpack-2-ebed3172fa8c

**Comment by skillxup** [comment]
its not working, the developer have to check twice before publishing

**Comment by navdeepsingh** [comment]
Hello @rkitonlinetrainings I understand your frustration. It is a very old project, I created for my Point of Concept that time. I am sorry for all problems you faced.  
I highly recommend not to follow this repo. You can ask me a specific logic issues that you are facing while development. Will be happy to help you around.
